POST /v1/engine/translate.json HTTP/1.1
Host: api.codic.jp
Authorization: Bearer A0DpLSALShLgmtCeTuezdNtpTKQlXlH1A7
content-type: application/json

{
    "project_id": "21109",
    "text": "1_酵素剤_燐酸(g)_WpT",
    "casing": "lower underscore"
}

###

GET /v1/user_projects.json
Host: api.codic.jp
Authorization: Bearer A0DpLSALShLgmtCeTuezdNtpTKQlXlH1A7

###

GET /v1/ced/lookup.json?query=phosphoric
Host: api.codic.jp
Authorization: Bearer A0DpLSALShLgmtCeTuezdNtpTKQlXlH1A7
